spring:
  application:
    name: import-service
  main:
    banner-mode: off
  rabbitmq:
    host: localhost
    port: 5672
    publisher-returns: true
    publisher-confirm-type: simple

app:
  labResultType: 1
  scheduling:
    enable: true

