server:
  port: 8888

spring:
  application:
    name: config-service
  main:
    banner-mode: off
  cloud:
    config:
      server:
        git:
          uri: https://github.com/alexander-mikhailov/techlead_project_config
