server:
  port: 8091

spring:
  application:
    name: processing-service
  main:
    banner-mode: off

app:
  scheduling:
    enable: true
  importServiceId: import-service

import-service:
  ribbon:
#    eureka:
#      enabled: false
    listOfServers: localhost:8081,localhost:8082
#    ServerListRefreshInterval: 30000
